# Generated by Django 4.2.6 on 2023-10-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='3', max_length=1),
        ),
    ]
