# Generated by Django 4.2.6 on 2023-10-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['creation_date']},
        ),
    ]
